== queries (q) 
to receive events from relays, you send them requests containing your queries

* relays will start sending events one by one that match the queries
* relays will keep relaying new events as they receive them until the request is closed
* by default events will be printed to the view

to send a raw request, type: .aa q req <relset> <query>

* <relset> is either a single relay URL or a relay set id
* <query> is a nostr request filter (JSON)
* "eose":"close" can be added to the query (this will close the request after all stored events have been returned)

example of a raw request that will be performed on relays that have the set "read":
.aa q req read {"kinds":[1],"limit":10,"eose":"close"}

the following variables can be used in queries as values:

inside timestamp fields (since,until);

* "now": converts to the timestamp of now
* "d_<date_string>": converts to a timestamp of 'date_string'. ex: "d_2024-08-21"
* "n_<number>": converts to a timestamp from <number> of days ago. ex: "n_1" converts to 1 day ago. 
* "h_<number>" for hours ago
* "m_<number>" for minutes ago
* "M_<number>" for months ago
* "y_<number>" for years ago

inside author field:

* "u": converts to your pubkey (if logged in)
* "k3": converts to a list of pubkeys you follow (if logged in)

example of query with variables: {"kinds":[1],"authors":["u"],"since":"n_7"}

you can store queries so it's easier to run them
to store a query, type: .aa q add <fid> <query>

* <fid> is a filter identifier with the following allowed characters: a-z_0-9
* <query> is explained above

to run a query on specific relays, type: .aa q run <fid> <relset>

* <fid> is explained above
* <relset> is a single relay url or a relay set; by leaving it empty, it defaults relset "read"

to run a query as outbox, type: .aa q out <fid>

to close a query, type: .aa q close <fid>

* if <fid> is omitted all opened queries will be closed instead


video::https://v.nostr.build/hzQufBzjStD8L8j6.mp4["example of running the query: a"]

example: .aa q run f, u, n